[platformio]
; create a separate file for user-specific settings
extra_configs = platformio.user.*.ini

[base_esp32]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
lib_deps =
	WiFi
	links2004/WebSockets@^2.7.3
	bblanchon/ArduinoJson@^7.4.3
    # renovate: datasource=git-refs depName=meshtastic-ArduinoThread packageName=https://github.com/meshtastic/ArduinoThread gitBranch=master
	https://github.com/meshtastic/ArduinoThread/archive/b841b0415721f1341ea41cccfb4adccfaf951567.zip
	# renovate: datasource=git-refs depName=jnthas-Improv-WiFi-Library packageName=https://github.com/jnthas/Improv-WiFi-Library gitBranch=main
	https://github.com/jnthas/Improv-WiFi-Library/archive/e37c244e0080349e191252acf4bce146eca118e0.zip

upload_speed = 921600
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder

build_flags =
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG

[env:esp32s2mini]
extends = base_esp32
board = lolin_s2_mini
build_flags =
	${base_esp32.build_flags}
	-D I2C_SDA=33
	-D I2C_SCL=35
	-D SERVO_PINS=1,2,4,6,8,10,13,14
	-D BUTTON_PINS=0,12

# untested
[env:esp32dev]
extends = base_esp32
board = esp32dev
build_flags =
	${base_esp32.build_flags}
	-D I2C_SDA=21
	-D I2C_SCL=22
	-D BUTTON_PINS=0

# untested
[env:distro_board_v1]
extends = base_esp32
board = esp32dev
build_flags =
	${base_esp32.build_flags}
	-D I2C_SDA=21
	-D I2C_SCL=22
	-D SERVO_PINS=15,2,23,19,4,16,17,18
	-D BUTTON_PINS=0

# untested
[env:distro_board_v2]
extends = base_esp32
board = esp32-s3-devkitm-1
board_build.mcu = esp32s3
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_flags =
	${base_esp32.build_flags}
	-D I2C_SDA=8
	-D I2C_SCL=9
	-D SERVO_PINS=4,5,6,7,15,16,17,18
	-D USB_CDC_ON_BOOT=0
	-D CDC_ON_BOOT_ENABLED=1
