#!/usr/bin/env python3
"""
Reads all files in the webui/ directory and generates:
  src/webui.cpp   - PROGMEM byte arrays (gzip compressed) + registerStaticUiFiles()
  include/webui.h - extern declarations + size constants + function declaration

Run from the project root:
  python3 tools/webui_to_code.py
"""

import gzip
import os
import re
import sys

try:
    _project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    _project_dir = os.path.abspath(os.getcwd())

WEBUI_DIR = os.path.join(_project_dir, "webui")
OUT_CPP = os.path.join(_project_dir, "src", "webui.cpp")
OUT_H = os.path.join(_project_dir, "include", "webui.h")

BYTES_PER_LINE = 16

# Maps file extension -> MIME type
MIME_TYPES = {
    ".html": "text/html",
    ".htm":  "text/html",
    ".css":  "text/css",
    ".js":   "application/javascript",
    ".mjs":  "application/javascript",
    ".json": "application/json",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif":  "image/gif",
    ".ico":  "image/x-icon",
    ".svg":  "image/svg+xml",
    ".woff": "font/woff",
    ".woff2":"font/woff2",
    ".ttf":  "font/ttf",
    ".txt":  "text/plain",
    ".xml":  "application/xml",
}
DEFAULT_MIME = "application/octet-stream"

# Files served additionally under "/" (checked as exact filename match)
ROOT_ALIASES = {"index.html"}


def path_to_varname(rel_path: str) -> str:
    """Convert a relative file path to a valid C identifier.

    index.html        -> webui_index_html
    assets/style.css  -> webui_assets_style_css
    """
    name = "webui_" + rel_path.replace(os.sep, "_").replace("/", "_")
    name = re.sub(r"[^0-9A-Za-z_]", "_", name)
    name = re.sub(r"^([0-9])", r"_\1", name)
    return name


def url_path(rel_path: str) -> str:
    """Convert a relative file path to a URL path (always forward slashes)."""
    return "/" + rel_path.replace(os.sep, "/")


def mime_for(rel_path: str) -> str:
    ext = os.path.splitext(rel_path)[1].lower()
    return MIME_TYPES.get(ext, DEFAULT_MIME)


def collect_files(webui_dir: str):
    """Return list of (rel_path, abs_path) sorted by rel_path."""
    files = []
    for root, dirs, filenames in os.walk(webui_dir):
        dirs.sort()
        for filename in sorted(filenames):
            abs_path = os.path.join(root, filename)
            rel_path = os.path.relpath(abs_path, webui_dir)
            files.append((rel_path, abs_path))
    return files


def bytes_to_c_array(data: bytes) -> str:
    """Convert bytes to a C hex initialiser list, 16 bytes per line."""
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines)


def make_handler(varname: str, mime: str) -> list[str]:
    """Return the lines of a single server.on() handler (no trailing newline)."""
    return [
        "    [](AsyncWebServerRequest *request) {",
        f'        AsyncWebServerResponse *r = request->beginResponse(200, "{mime}",',
        f"            {varname}_data, {varname}_size);",
        '        r->addHeader("Content-Encoding", "gzip");',
        "        request->send(r);",
        "    }",
    ]


def main():
    webui_dir = os.path.realpath(WEBUI_DIR)
    print(f"\nBuilding web UI from: {os.path.relpath(webui_dir, _project_dir)}")

    if not os.path.isdir(webui_dir):
        print(f"ERROR: webui directory not found: {webui_dir}", file=sys.stderr)
        sys.exit(1)

    files = collect_files(webui_dir)
    if not files:
        print("WARNING: no files found in webui/", file=sys.stderr)

    entries = []  # (varname, rel_path, mime, compressed_bytes)
    for rel_path, abs_path in files:
        with open(abs_path, "rb") as f:
            raw = f.read()
        compressed = gzip.compress(raw, compresslevel=9)
        varname = path_to_varname(rel_path)
        mime = mime_for(rel_path)
        entries.append((varname, rel_path, mime, compressed))
        print(f"  {rel_path}: {len(raw)} bytes -> {len(compressed)} bytes (gzip)")

    # ------------------------------------------------------------------
    # Generate include/webui.h
    # ------------------------------------------------------------------
    h_lines = [
        "// Auto-generated by tools/webui_to_code.py — do not edit manually.",
        "#pragma once",
        "#include <Arduino.h>",
        "#include <ESPAsyncWebServer.h>",
        "",
    ]
    for varname, rel_path, mime, data in entries:
        h_lines.append(f"// {rel_path}")
        h_lines.append(f"extern const unsigned char {varname}_data[] PROGMEM;")
        h_lines.append(f"extern const size_t {varname}_size;")
        h_lines.append("")
    h_lines.append("void registerStaticUiFiles(AsyncWebServer &server);")
    h_lines.append("")

    h_content = "\n".join(h_lines) + "\n"

    # ------------------------------------------------------------------
    # Generate src/webui.cpp
    # ------------------------------------------------------------------
    cpp_lines = [
        "// Auto-generated by tools/webui_to_code.py — do not edit manually.",
        '#include "webui.h"',
        "",
    ]

    # Byte arrays
    for varname, rel_path, mime, data in entries:
        array_body = bytes_to_c_array(data)
        cpp_lines.append(f"// {rel_path} (gzip compressed)")
        cpp_lines.append(f"const unsigned char {varname}_data[] PROGMEM = {{")
        cpp_lines.append(array_body)
        cpp_lines.append("};")
        cpp_lines.append(f"const size_t {varname}_size = sizeof({varname}_data);")
        cpp_lines.append("")

    # registerStaticUiFiles()
    cpp_lines.append("void registerStaticUiFiles(AsyncWebServer &server) {")
    for varname, rel_path, mime, data in entries:
        path = url_path(rel_path)
        handler_lines = make_handler(varname, mime)
        cpp_lines.append(f"  // {rel_path}")
        cpp_lines.append(f'  server.on("{path}", HTTP_GET,')
        cpp_lines.extend(f"  {l}" for l in handler_lines)
        cpp_lines.append("  );")

        # Extra alias: register root "/" for index.html
        filename = os.path.basename(rel_path)
        if filename in ROOT_ALIASES and path != "/":
            cpp_lines.append(f'  server.on("/", HTTP_GET,')
            cpp_lines.extend(f"  {l}" for l in handler_lines)
            cpp_lines.append("  );")

        cpp_lines.append("")

    cpp_lines.append("}")
    cpp_lines.append("")

    cpp_content = "\n".join(cpp_lines) + "\n"

    # ------------------------------------------------------------------
    # Write files
    # ------------------------------------------------------------------
    os.makedirs(os.path.dirname(os.path.realpath(OUT_H)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.realpath(OUT_CPP)), exist_ok=True)

    with open(OUT_H, "w") as f:
        f.write(h_content)
    print(f"Written: {os.path.relpath(OUT_H, _project_dir)}")

    with open(OUT_CPP, "w") as f:
        f.write(cpp_content)
    print(f"Written: {os.path.relpath(OUT_CPP, _project_dir)}")
    print("")


main()
